import type {
  ToolSpec,
  ExportResult,
  ExportFile,
  OutputLang,
  JsonSchema,
  HandlerStep,
} from "../types.js";

export interface SnippetOptions {
  lang: OutputLang;
  domain: string;
}

export function generateSnippet(
  tools: ToolSpec[],
  options: SnippetOptions
): ExportResult {
  const { lang, domain } = options;
  const ext = lang === "ts" ? "ts" : "js";

  const files: ExportFile[] = [];

  const mainContent = generateMainFile(tools, lang);
  files.push({
    name: `webmcp.tools.${ext}`,
    content: mainContent,
    language: lang === "ts" ? "typescript" : "javascript",
  });

  return { files, target: "snippet" };
}

function generateMainFile(tools: ToolSpec[], lang: OutputLang): string {
  const lines: string[] = [];

  lines.push("/**");
  lines.push(" * WebMCP Tool Definitions");
  lines.push(" * Auto-generated by webmcp-autogen");
  lines.push(` * Generated: ${new Date().toISOString()}`);
  lines.push(" *");
  lines.push(" * Usage: Include this script on your page to register tools");
  lines.push(" * with the browser's Model Context Protocol.");
  lines.push(" */");
  lines.push("");

  lines.push("// Check for WebMCP API support (Chrome 146+)");
  if (lang === "ts") {
    lines.push("declare global {");
    lines.push("  interface Navigator {");
    lines.push("    modelContext?: {");
    lines.push("      registerTool(def: {");
    lines.push("        name: string;");
    lines.push("        description: string;");
    lines.push("        inputSchema: Record<string, unknown>;");
    lines.push("        annotations?: Record<string, string>;");
    lines.push("        execute: (params: Record<string, unknown>) => Promise<{ content: Array<{ type: string; text: string }> }>;");
    lines.push("      }): void;");
    lines.push("      unregisterTool(name: string): void;");
    lines.push("    };");
    lines.push("  }");
    lines.push("}");
    lines.push("");
  }

  lines.push("function initWebMCPTools() {");
  lines.push("  if (!navigator.modelContext) {");
  lines.push('    console.warn("[WebMCP] navigator.modelContext not available. Ensure Chrome 146+ with experimental features enabled.");');
  lines.push("    return;");
  lines.push("  }");
  lines.push("");

  for (const tool of tools) {
    lines.push(`  // Tool: ${tool.name}`);
    lines.push(`  // Safety: ${tool.safety.level}${tool.safety.requiresConfirm ? " (requires confirmation)" : ""}`);
    lines.push(`  // Source: ${tool.provenance.pageUrl}`);
    lines.push("  navigator.modelContext.registerTool({");
    lines.push(`    name: ${JSON.stringify(tool.name)},`);
    lines.push(`    description: ${JSON.stringify(tool.description)},`);

    lines.push(`    inputSchema: ${indent(JSON.stringify(tool.inputSchema, null, 2), 4)},`);

    // Chrome WebMCP annotations for safety hints
    const annotations: Record<string, string> = {};
    if (tool.safety.level === "read") annotations.readOnlyHint = "true";
    if (tool.safety.level === "danger") annotations.destructiveHint = "true";
    if (Object.keys(annotations).length > 0) {
      lines.push(`    annotations: ${JSON.stringify(annotations)},`);
    }

    lines.push(`    execute: async (params${lang === "ts" ? ": Record<string, unknown>" : ""}) => {`);
    lines.push(...generateHandlerBody(tool, 6));
    lines.push("    },");
    lines.push("  });");
    lines.push("");
  }

  lines.push(`  console.log("[WebMCP] Registered ${tools.length} tool${tools.length !== 1 ? "s" : ""}");`);
  lines.push("}");
  lines.push("");

  lines.push("// Initialize when DOM is ready");
  lines.push('if (document.readyState === "loading") {');
  lines.push('  document.addEventListener("DOMContentLoaded", initWebMCPTools);');
  lines.push("} else {");
  lines.push("  initWebMCPTools();");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function generateHandlerBody(tool: ToolSpec, indentLevel: number): string[] {
  const lines: string[] = [];
  const pad = " ".repeat(indentLevel);
  const template = tool.implementation.handlerTemplate;

  if (!template || !template.steps.length) {
    lines.push(`${pad}// TODO: Implement execute for ${tool.name}`);
    lines.push(`${pad}return { content: [{ type: "text", text: "Done" }] };`);
    return lines;
  }

  for (const step of template.steps) {
    lines.push(...generateStep(step, pad));
  }

  return lines;
}

function generateStep(step: HandlerStep, pad: string): string[] {
  const lines: string[] = [];

  switch (step.step) {
    case "ensure_page": {
      const pathname = new URL(step.urlPattern).pathname;
      if (pathname !== "/") {
        lines.push(`${pad}// Ensure we're on the right page`);
        lines.push(`${pad}if (!window.location.pathname.startsWith(${JSON.stringify(pathname)})) {`);
        lines.push(`${pad}  window.location.href = ${JSON.stringify(step.urlPattern)};`);
        lines.push(`${pad}  await new Promise(resolve => setTimeout(resolve, 2000));`);
        lines.push(`${pad}}`);
      }
      lines.push("");
      break;
    }

    case "fill_form": {
      lines.push(`${pad}// Fill form fields`);
      lines.push(`${pad}const form = document.querySelector(${JSON.stringify(step.formSelector)});`);
      lines.push(`${pad}if (!form) throw new Error("Form not found: ${step.formSelector}");`);
      lines.push("");
      for (const [fieldName, paramExpr] of Object.entries(step.mapping)) {
        const paramKey = paramExpr.replace("params.", "");
        lines.push(`${pad}const ${safeName(fieldName)}Input = form.querySelector('[name="${fieldName}"]');`);
        lines.push(`${pad}if (${safeName(fieldName)}Input) {`);
        lines.push(`${pad}  ${safeName(fieldName)}Input.value = String(params["${paramKey}"] ?? "");`);
        lines.push(`${pad}  ${safeName(fieldName)}Input.dispatchEvent(new Event("input", { bubbles: true }));`);
        lines.push(`${pad}}`);
        lines.push("");
      }
      break;
    }

    case "click": {
      lines.push(`${pad}// Click element`);
      lines.push(`${pad}const clickTarget = document.querySelector(${JSON.stringify(step.selector)});`);
      lines.push(`${pad}if (clickTarget) {`);
      lines.push(`${pad}  (clickTarget as HTMLElement).click();`);
      lines.push(`${pad}}`);
      if (step.waitFor) {
        lines.push(`${pad}await new Promise(resolve => setTimeout(resolve, 1000));`);
      }
      lines.push("");
      break;
    }

    case "wait_network": {
      lines.push(`${pad}// Wait for network response`);
      lines.push(`${pad}const response = await new Promise((resolve, reject) => {`);
      lines.push(`${pad}  const timeout = setTimeout(() => reject(new Error("Network timeout")), 10000);`);
      lines.push(`${pad}  const origFetch = window.fetch;`);
      lines.push(`${pad}  window.fetch = async (...args) => {`);
      lines.push(`${pad}    const res = await origFetch(...args);`);
      if (step.match.urlIncludes) {
        lines.push(`${pad}    if (String(args[0]).includes(${JSON.stringify(step.match.urlIncludes)})) {`);
      } else {
        lines.push(`${pad}    {`);
      }
      lines.push(`${pad}      clearTimeout(timeout);`);
      lines.push(`${pad}      window.fetch = origFetch;`);
      lines.push(`${pad}      resolve(res.clone());`);
      lines.push(`${pad}    }`);
      lines.push(`${pad}    return res;`);
      lines.push(`${pad}  };`);
      lines.push(`${pad}});`);
      lines.push("");
      break;
    }

    case "wait_element": {
      lines.push(`${pad}// Wait for element to appear`);
      lines.push(`${pad}await new Promise((resolve) => {`);
      lines.push(`${pad}  const check = () => {`);
      lines.push(`${pad}    if (document.querySelector(${JSON.stringify(step.selector)})) {`);
      lines.push(`${pad}      resolve(undefined);`);
      lines.push(`${pad}    } else {`);
      lines.push(`${pad}      requestAnimationFrame(check);`);
      lines.push(`${pad}    }`);
      lines.push(`${pad}  };`);
      lines.push(`${pad}  check();`);
      lines.push(`${pad}});`);
      lines.push("");
      break;
    }

    case "extract": {
      lines.push(`${pad}// Extract data from page`);
      lines.push(`${pad}const extracted = document.querySelector(${JSON.stringify(step.selector)});`);
      if (step.attribute) {
        lines.push(`${pad}const extractedValue = extracted?.getAttribute(${JSON.stringify(step.attribute)}) ?? null;`);
      } else {
        lines.push(`${pad}const extractedValue = extracted?.textContent ?? null;`);
      }
      lines.push("");
      break;
    }

    case "return": {
      lines.push(`${pad}return { content: [{ type: "text", text: "Done" }] };`);
      break;
    }
  }

  return lines;
}

function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line, i) => (i === 0 ? line : pad + line))
    .join("\n");
}

function safeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_$]/g, "_");
}
