import type { ToolSpec, ExportResult, ExportFile } from "../types.js";

export interface UserscriptOptions {
  domain: string;
}

export function generateUserscript(
  tools: ToolSpec[],
  options: UserscriptOptions
): ExportResult {
  const lines: string[] = [];

  lines.push("// ==UserScript==");
  lines.push(`// @name         WebMCP Tools for ${options.domain}`);
  lines.push("// @namespace    https://webmcp.dev/userscripts");
  lines.push("// @version      1.0.0");
  lines.push(`// @description  WebMCP tool definitions for ${options.domain} — auto-generated by webmcp-autogen`);
  lines.push(`// @match        https://${options.domain}/*`);
  lines.push(`// @match        https://www.${options.domain}/*`);
  lines.push("// @grant        none");
  lines.push("// @run-at       document-idle");
  lines.push("// ==/UserScript==");
  lines.push("");
  lines.push("(function() {");
  lines.push('  "use strict";');
  lines.push("");
  lines.push("  if (!navigator.modelContext) {");
  lines.push('    console.warn("[WebMCP Userscript] navigator.modelContext not available.");');
  lines.push("    return;");
  lines.push("  }");
  lines.push("");

  for (const tool of tools) {
    lines.push(`  // Tool: ${tool.name} (${tool.safety.level})`);
    lines.push("  navigator.modelContext.registerTool({");
    lines.push(`    name: ${JSON.stringify(tool.name)},`);
    lines.push(`    description: ${JSON.stringify(tool.description)},`);
    lines.push(`    inputSchema: ${JSON.stringify(tool.inputSchema)},`);
    lines.push("    handler: async (params) => {");
    lines.push(`      // TODO: Implement ${tool.name} handler`);
    lines.push("      return { success: true };");
    lines.push("    },");
    lines.push("  });");
    lines.push("");
  }

  lines.push(`  console.log("[WebMCP Userscript] Registered ${tools.length} tools for ${options.domain}");`);
  lines.push("})();");
  lines.push("");

  const files: ExportFile[] = [
    {
      name: `webmcp.${sanitize(options.domain)}.user.js`,
      content: lines.join("\n"),
      language: "javascript",
    },
  ];

  return { files, target: "userscript" };
}

function sanitize(domain: string): string {
  return domain.replace(/[^a-z0-9.-]/gi, "_").toLowerCase();
}
