import type { ToolSpec, ExportResult, ExportFile } from "../types.js";

export interface YamlOptions {
  domain: string;
}

export function generateYaml(
  tools: ToolSpec[],
  options: YamlOptions
): ExportResult {
  const lines: string[] = [];

  lines.push("# WebMCP Tool Definitions");
  lines.push(`# Domain: ${options.domain}`);
  lines.push(`# Generated by webmcp-autogen on ${new Date().toISOString()}`);
  lines.push(`# Tools: ${tools.length}`);
  lines.push("");
  lines.push(`version: "1.0"`);
  lines.push(`domain: ${quote(options.domain)}`);
  lines.push("");
  lines.push("tools:");

  for (const tool of tools) {
    lines.push(`  - name: ${quote(tool.name)}`);
    lines.push(`    description: ${quote(tool.description)}`);
    lines.push(`    safety:`);
    lines.push(`      level: ${tool.safety.level}`);
    lines.push(`      requiresConfirm: ${tool.safety.requiresConfirm}`);
    lines.push(`    availability:`);
    lines.push(`      urlPatterns:`);
    for (const pattern of tool.availability.urlPatterns) {
      lines.push(`        - ${quote(pattern)}`);
    }
    lines.push(`      requiresAuth: ${tool.availability.requiresAuth}`);
    lines.push(`    inputSchema:`);
    lines.push(objectToYaml(tool.inputSchema as unknown as Record<string, unknown>, 6));
    lines.push(`    implementation:`);
    lines.push(`      kind: ${tool.implementation.kind}`);
    if (tool.implementation.form) {
      lines.push(`      form:`);
      lines.push(`        formSelector: ${quote(tool.implementation.form.formSelector)}`);
      lines.push(`        toolautosubmit: ${tool.implementation.form.toolautosubmit ?? false}`);
    }
    lines.push("");
  }

  const files: ExportFile[] = [
    {
      name: "webmcp.tools.yaml",
      content: lines.join("\n") + "\n",
      language: "yaml",
    },
  ];

  return { files, target: "yaml" };
}

function quote(value: string): string {
  if (
    value.includes(":") ||
    value.includes("#") ||
    value.includes("'") ||
    value.includes('"') ||
    value.includes("\n") ||
    value.startsWith(" ") ||
    value.endsWith(" ")
  ) {
    return JSON.stringify(value);
  }
  return value;
}

function objectToYaml(obj: Record<string, unknown>, indent: number): string {
  const lines: string[] = [];
  const pad = " ".repeat(indent);

  for (const [key, value] of Object.entries(obj)) {
    if (value === null || value === undefined) continue;

    if (typeof value === "object" && !Array.isArray(value)) {
      lines.push(`${pad}${key}:`);
      lines.push(objectToYaml(value as Record<string, unknown>, indent + 2));
    } else if (Array.isArray(value)) {
      lines.push(`${pad}${key}:`);
      for (const item of value) {
        if (typeof item === "object") {
          lines.push(`${pad}  -`);
          lines.push(objectToYaml(item as Record<string, unknown>, indent + 4));
        } else {
          lines.push(`${pad}  - ${quote(String(item))}`);
        }
      }
    } else if (typeof value === "string") {
      lines.push(`${pad}${key}: ${quote(value)}`);
    } else {
      lines.push(`${pad}${key}: ${value}`);
    }
  }

  return lines.join("\n");
}
